import { basePrompt } from './base'
import { lvglSkill } from './skills/lvgl'
import { audioSkill } from './skills/audio'
import { cameraSkill } from './skills/camera'
import { imuSkill } from './skills/imu'
import { wifiSkill } from './skills/wifi'
import { bleSkill } from './skills/ble'
import { sdcardSkill } from './skills/sdcard'
import { gpioSkill } from './skills/gpio'
import { speechSkill } from './skills/speech'
import { visionSkill } from './skills/vision'
import { handheldSkill } from './skills/handheld'

export const ALL_SKILLS = [
  lvglSkill,
  audioSkill,
  cameraSkill,
  imuSkill,
  wifiSkill,
  bleSkill,
  sdcardSkill,
  gpioSkill,
  speechSkill,
  visionSkill,
  handheldSkill,
]

// Build system prompt from base + selected skill ids
export function buildSystemPrompt(selectedSkillIds = []) {
  const skillPrompts = ALL_SKILLS
    .filter(s => selectedSkillIds.includes(s.id))
    .map(s => s.systemPrompt)
    .join('\n\n')
  return skillPrompts ? `${basePrompt}\n\n${skillPrompts}` : basePrompt
}

// Build complete ESP-IDF project files from selected skills
// Returns { 'CMakeLists.txt': '...', 'main/CMakeLists.txt': '...', ... }
export function buildProjectFiles(projectName, selectedSkillIds = []) {
  const skills = ALL_SKILLS.filter(s => selectedSkillIds.includes(s.id))
  const configs = skills.map(s => s.projectConfig).filter(Boolean)

  // Merge srcs (deduplicate)
  const srcs = ['main.c', ...new Set(configs.flatMap(c => c.srcs || []))]

  // Merge sdkconfig (deduplicate)
  const sdkBase = [
    '# Generated by esp32-vibe-coder',
    'CONFIG_IDF_TARGET="esp32s3"',
    'CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y',
  ]
  const sdkExtra = [...new Set(configs.flatMap(c => c.sdkconfig || []))]
  const sdkconfig = [...sdkBase, ...sdkExtra].join('\n')

  // Merge idf_component.yml (deduplicate)
  const components = [...new Set(configs.flatMap(c => c.idfComponents || []))]
  const idfComponentYml = components.length > 0
    ? `## IDF Component Manager Manifest File\ndependencies:\n` +
      components.map(c => `  ${c}`).join('\n') +
      `\n  idf:\n    version: ">=5.0"`
    : null

  // Partitions: use the most comprehensive one (most lines wins)
  const allPartitions = configs.map(c => c.partitions).filter(Boolean)
  const partitionsCsv = allPartitions.length > 0
    ? allPartitions.reduce((a, b) => a.length >= b.length ? a : b).join('\n')
    : null

  // spiffs image
  const needsSpiffs = configs.some(c => c.spiffs)

  // compile options
  const compileOpts = [...new Set(configs.flatMap(c => c.compileOptions || []))]

  // main/CMakeLists.txt
  const srcList = srcs.map(s => `"${s}"`).join('\n                    ')
  let mainCmake = `idf_component_register(SRCS ${srcList}\n                    INCLUDE_DIRS ".")`
  if (needsSpiffs) {
    mainCmake += `\n\nspiffs_create_partition_image(storage ../spiffs FLASH_IN_PROJECT)`
  }
  if (compileOpts.length > 0) {
    mainCmake += `\ntarget_compile_options(\${COMPONENT_LIB} PRIVATE ${compileOpts.join(' ')})`
  }

  // root CMakeLists.txt
  const rootCmake =
`cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(${projectName})`

  const files = {
    'CMakeLists.txt': rootCmake,
    'main/CMakeLists.txt': mainCmake,
    'sdkconfig.defaults': sdkconfig,
  }
  if (idfComponentYml) files['main/idf_component.yml'] = idfComponentYml
  if (partitionsCsv)   files['partitions.csv'] = partitionsCsv

  return files
}

// Patch a skill's systemPrompt at runtime (self-evolution)
export function patchSkill(skillId, type, content) {
  const skill = ALL_SKILLS.find(s => s.id === skillId)
  if (!skill) return null
  const section = type === 'pitfall' ? '### Pitfalls' : '### Usage'
  const entry = `- ${content}`
  if (skill.systemPrompt.includes(section)) {
    skill.systemPrompt = skill.systemPrompt.replace(section, `${section}\n${entry}`)
  } else {
    skill.systemPrompt += `\n\n${section}\n${entry}`
  }
  return skill
}
